apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "spring-boot"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot
        component: api
    spec:
      containers:
        - name: spring-boot
          image: gcr.io/cloudjlb-eventer/spring-boot-app:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 8080
